// Generated by CoffeeScript 1.7.1
(function() {
  (function(doc, $) {
    var $body, $window, position, _debounce;
    $body = null;
    $window = $(window);
    position = function() {
      var $reference, $self, left, offset, ref_height, self_height, self_width, top;
      $reference = this.$reference, $self = this.$self;
      if (!$reference.is(':visible')) {
        return;
      }
      offset = $reference.offset();
      self_width = parseInt($self.width());
      self_height = parseInt($self.height());
      ref_height = parseInt($reference.outerHeight());
      left = $window.width() + $window.scrollLeft() - (offset.left + self_width + 15);
      top = $window.height() + $window.scrollTop() - (offset.top + ref_height + self_height + 15);
      $self.css({
        top: top >= 0 && (offset.top + ref_height) || (offset.top - self_height - 15),
        left: offset.left + Math.min(0, left)
      });
      if ($self.is(':visible')) {
        return typeof _callback === "function" ? _callback() : void 0;
      }
    };
    _debounce = function(fn, t) {
      var _delay;
      if (t == null) {
        t = 10;
      }
      _delay = null;
      return function() {
        clearTimeout(_delay);
        return _delay = setTimeout(fn, t);
      };
    };

    /*
    	 * @param boolean repin -
     */
    return $.fn.floatable = function($reference, _callback, repin) {
      if (repin == null) {
        repin = true;
      }
      return this.each(function() {
        var $self, _position;
        $self = $(this);
        $body || ($body = $('body'));
        if ($self.data('floatable')) {
          return;
        }
        if (repin) {
          $body.append($self.remove());
        }
        $reference.bind('click', _position = position.bind({
          $reference: $reference,
          $self: $self
        }));
        $window.bind({
          'resize': _position,
          'scroll': _debounce(_position)
        });
        _position();
        return $self.data('floatable', true);
      });
    };
  })(document, jQuery);

}).call(this);
